version: "3"
services:
  standalone:
    image: apachepulsar/pulsar
    container_name: pulsar.local
    ports:
      - 8080:8080
      - 6650:6650
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    volumes:
      - /opt/pulsar/data:/data
      - /opt/pulsar/conf:/conf
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"

networks:
  default:
    external:
      name: test-dev-shared-network